
package vision;

import javax.swing.JFrame;


public class MenuPrincipal extends javax.swing.JFrame {


    public MenuPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMLogin = new javax.swing.JMenu();
        jMiLoginClient = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMLoginCompany = new javax.swing.JMenu();
        jMiLoginAirline = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMiLoginHotel = new javax.swing.JMenuItem();
        jMSignOut = new javax.swing.JMenu();
        jMiSignClient = new javax.swing.JMenuItem();
        jMSignCompany = new javax.swing.JMenu();
        jMiSignAirLine = new javax.swing.JMenuItem();
        jMiSignHotel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jMLogin.setMnemonic('L');
        jMLogin.setText("Login");

        jMiLoginClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMiLoginClient.setText("Client");
        jMiLoginClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiLoginClientActionPerformed(evt);
            }
        });
        jMLogin.add(jMiLoginClient);
        jMLogin.add(jSeparator1);

        jMLoginCompany.setMnemonic('Y');
        jMLoginCompany.setText("Company");

        jMiLoginAirline.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMiLoginAirline.setText("AirLine");
        jMiLoginAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiLoginAirlineActionPerformed(evt);
            }
        });
        jMLoginCompany.add(jMiLoginAirline);
        jMLoginCompany.add(jSeparator2);

        jMiLoginHotel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMiLoginHotel.setText("Hotel");
        jMiLoginHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiLoginHotelActionPerformed(evt);
            }
        });
        jMLoginCompany.add(jMiLoginHotel);

        jMLogin.add(jMLoginCompany);

        jMenuBar1.add(jMLogin);

        jMSignOut.setMnemonic('S');
        jMSignOut.setText("Sign out");

        jMiSignClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMiSignClient.setText("Client");
        jMiSignClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiSignClientActionPerformed(evt);
            }
        });
        jMSignOut.add(jMiSignClient);

        jMSignCompany.setMnemonic('Y');
        jMSignCompany.setText("Company");

        jMiSignAirLine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMiSignAirLine.setText("AirLine");
        jMiSignAirLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiSignAirLineActionPerformed(evt);
            }
        });
        jMSignCompany.add(jMiSignAirLine);

        jMiSignHotel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMiSignHotel.setText("Hotel");
        jMiSignHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiSignHotelActionPerformed(evt);
            }
        });
        jMSignCompany.add(jMiSignHotel);

        jMSignOut.add(jMSignCompany);

        jMenuBar1.add(jMSignOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMiLoginClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiLoginClientActionPerformed

        LoginClient tela = new LoginClient();
        jDesktop.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_jMiLoginClientActionPerformed

    private void jMiLoginAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiLoginAirlineActionPerformed

        LoginAirLine tela = new LoginAirLine();
        jDesktop.add(tela);
        tela.setVisible(true);       
    }//GEN-LAST:event_jMiLoginAirlineActionPerformed

    private void jMiLoginHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiLoginHotelActionPerformed

        LoginHotel tela = new LoginHotel();
        jDesktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMiLoginHotelActionPerformed

    private void jMiSignClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiSignClientActionPerformed

        SignOutClient tela = new SignOutClient();
        jDesktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMiSignClientActionPerformed

    private void jMiSignAirLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiSignAirLineActionPerformed

        SignOutAirLine tela = new SignOutAirLine();
        jDesktop.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_jMiSignAirLineActionPerformed

    private void jMiSignHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiSignHotelActionPerformed

        SignOutHotel tela = new SignOutHotel();
        jDesktop.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMiSignHotelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMLogin;
    private javax.swing.JMenu jMLoginCompany;
    private javax.swing.JMenu jMSignCompany;
    private javax.swing.JMenu jMSignOut;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMiLoginAirline;
    private javax.swing.JMenuItem jMiLoginClient;
    private javax.swing.JMenuItem jMiLoginHotel;
    private javax.swing.JMenuItem jMiSignAirLine;
    private javax.swing.JMenuItem jMiSignClient;
    private javax.swing.JMenuItem jMiSignHotel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
